# Generated by Django 6.0.6 on 2026-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('organizacao', models.CharField(max_length=150)),
                ('cargo_funcao', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade_estado', models.CharField(max_length=100)),
                ('segmento', models.CharField(choices=[('prefeitura', 'Prefeitura / Órgão Público'), ('construtora', 'Construtora / Incorporadora'), ('arquitetura', 'Arquitetura / Engenharia'), ('academia', 'Academia / Pesquisa'), ('outro', 'Outro')], max_length=20)),
                ('como_ajudar', models.CharField(choices=[('agendar_demo', 'Agendar Demo'), ('participar_piloto', 'Participar do Piloto'), ('proposta_parceria', 'Proposta de Parceria'), ('mais_informacoes', 'Mais Informações')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
