# Generated by Django 6.0.6 on 2026-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='mensagem',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cargo_funcao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cidade_estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='como_ajudar',
            field=models.CharField(choices=[('agendar_demo', 'Agendar Demo'), ('participar_piloto', 'Participar do Piloto'), ('proposta_parceria', 'Proposta de Parceria'), ('mais_informacoes', 'Mais Informações')], default='agendar_demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nome_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='segmento',
            field=models.CharField(blank=True, choices=[('prefeitura', 'Prefeitura / Órgão Público'), ('construtora', 'Construtora / Incorporadora'), ('arquitetura', 'Arquitetura / Engenharia'), ('academia', 'Academia / Pesquisa'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
