# Generated by Django 6.0.6 on 2026-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options_lead_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consentimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='origem',
            field=models.CharField(blank=True, default='site', max_length=100),
        ),
    ]
